package repositorio;


/**
* repositorio/ArchivoDetalles.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Wednesday, August 30, 2017 4:08:42 PM CEST
*/

public final class ArchivoDetalles implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public String archivo = null;
  public String directorio = null;
  public String palabrasClave[] = null;
  public String comentario = null;

  public ArchivoDetalles ()
  {
  } // ctor

  public ArchivoDetalles (String _nombre, String _archivo, String _directorio, String[] _palabrasClave, String _comentario)
  {
    nombre = _nombre;
    archivo = _archivo;
    directorio = _directorio;
    palabrasClave = _palabrasClave;
    comentario = _comentario;
  } // ctor

} // class ArchivoDetalles
