package repositorio;

/**
* repositorio/CoincidenciaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Wednesday, August 30, 2017 12:59:48 AM CEST
*/

public final class CoincidenciaHolder implements org.omg.CORBA.portable.Streamable
{
  public repositorio.Coincidencia value = null;

  public CoincidenciaHolder ()
  {
  }

  public CoincidenciaHolder (repositorio.Coincidencia initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = repositorio.CoincidenciaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    repositorio.CoincidenciaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return repositorio.CoincidenciaHelper.type ();
  }

}
