package repositorio;


/**
* repositorio/CoincidenciaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Wednesday, August 30, 2017 4:08:42 PM CEST
*/

abstract public class CoincidenciaHelper
{
  private static String  _id = "IDL:repositorio/Coincidencia:1.0";

  public static void insert (org.omg.CORBA.Any a, repositorio.Coincidencia that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static repositorio.Coincidencia extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nombreRepositorio",
            _tcOf_members0,
            null);
          _tcOf_members0 = repositorio.IRepositorioHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "repositorio",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "nombre",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "archivo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (repositorio.StringSeqHelper.id (), "StringSeq", _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "palabrasClave",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "comentario",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (repositorio.CoincidenciaHelper.id (), "Coincidencia", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static repositorio.Coincidencia read (org.omg.CORBA.portable.InputStream istream)
  {
    repositorio.Coincidencia value = new repositorio.Coincidencia ();
    value.nombreRepositorio = istream.read_string ();
    value.repositorio = repositorio.IRepositorioHelper.read (istream);
    value.nombre = istream.read_string ();
    value.archivo = istream.read_string ();
    value.palabrasClave = repositorio.StringSeqHelper.read (istream);
    value.comentario = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, repositorio.Coincidencia value)
  {
    ostream.write_string (value.nombreRepositorio);
    repositorio.IRepositorioHelper.write (ostream, value.repositorio);
    ostream.write_string (value.nombre);
    ostream.write_string (value.archivo);
    repositorio.StringSeqHelper.write (ostream, value.palabrasClave);
    ostream.write_string (value.comentario);
  }

}
