package repositorio;


/**
* repositorio/IRepositorioSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Wednesday, August 30, 2017 12:59:47 AM CEST
*/

public final class IRepositorioSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public repositorio.IRepositorio value[] = null;

  public IRepositorioSeqHolder ()
  {
  }

  public IRepositorioSeqHolder (repositorio.IRepositorio[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = repositorio.IRepositorioSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    repositorio.IRepositorioSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return repositorio.IRepositorioSeqHelper.type ();
  }

}
