package repositorio;


/**
* repositorio/IRepositorio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Tuesday, August 29, 2017 12:22:07 AM CEST
*/

public interface IRepositorio extends IRepositorioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IRepositorio
