package repositorio;


/**
* repositorio/IRepositorioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Tuesday, August 29, 2017 6:17:14 PM CEST
*/

public interface IRepositorioOperations 
{

  ///////////////////////////////////
  repositorio.IRepositorio padre ();

  ///////////////////////////////////
  void padre (repositorio.IRepositorio newPadre);
  repositorio.IRepositorio[] subordinados ();
  String nombre ();
  void nombre (String newNombre);

  // TODO Búsqueda por palabras clave
  repositorio.Coincidencia[] buscar (String palabraClave);

  // TODO Recuperar documentos
  void iniciarDescarga (String nombre);
  byte[] solicitarBloque (String nombre);

  // Registrar repositorios subordinados
  String registrar (repositorio.IRepositorio referencia);
  String registrarConNombre (repositorio.IRepositorio referencia, String nombre);

  // Dar de baja un repositorio
  void baja (String nombre);
} // interface IRepositorioOperations
