package repositorio;

/**
* repositorio/ITransferenciaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Wednesday, August 30, 2017 12:59:48 AM CEST
*/


///////////////////////////////////
public final class ITransferenciaHolder implements org.omg.CORBA.portable.Streamable
{
  public repositorio.ITransferencia value = null;

  public ITransferenciaHolder ()
  {
  }

  public ITransferenciaHolder (repositorio.ITransferencia initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = repositorio.ITransferenciaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    repositorio.ITransferenciaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return repositorio.ITransferenciaHelper.type ();
  }

}
