package repositorio;


/**
* repositorio/ITransferenciaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Wednesday, August 30, 2017 4:08:42 PM CEST
*/


///////////////////////////////////
abstract public class ITransferenciaHelper
{
  private static String  _id = "IDL:repositorio/ITransferencia:1.0";

  public static void insert (org.omg.CORBA.Any a, repositorio.ITransferencia that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static repositorio.ITransferencia extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (repositorio.ITransferenciaHelper.id (), "ITransferencia");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static repositorio.ITransferencia read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ITransferenciaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, repositorio.ITransferencia value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static repositorio.ITransferencia narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof repositorio.ITransferencia)
      return (repositorio.ITransferencia)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      repositorio._ITransferenciaStub stub = new repositorio._ITransferenciaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static repositorio.ITransferencia unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof repositorio.ITransferencia)
      return (repositorio.ITransferencia)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      repositorio._ITransferenciaStub stub = new repositorio._ITransferenciaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
