package repositorio;


/**
* repositorio/ITransferenciaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Wednesday, August 30, 2017 12:59:48 AM CEST
*/


///////////////////////////////////
public interface ITransferenciaOperations 
{
  byte[] solicitarBloque () throws repositorio.ArchivoNoEncontradoException;
} // interface ITransferenciaOperations
