package repositorio;


/**
* repositorio/RegistroNoPosibleException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Wednesday, August 30, 2017 4:08:42 PM CEST
*/

public final class RegistroNoPosibleException extends org.omg.CORBA.UserException
{

  public RegistroNoPosibleException ()
  {
    super(RegistroNoPosibleExceptionHelper.id());
  } // ctor


  public RegistroNoPosibleException (String $reason)
  {
    super(RegistroNoPosibleExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class RegistroNoPosibleException
