package repositorio;

/**
* repositorio/RegistroNoPosibleExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Dev/workspace352/OrgRepos/idl/IRepositorio.idl
* Wednesday, August 30, 2017 4:08:42 PM CEST
*/

public final class RegistroNoPosibleExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public repositorio.RegistroNoPosibleException value = null;

  public RegistroNoPosibleExceptionHolder ()
  {
  }

  public RegistroNoPosibleExceptionHolder (repositorio.RegistroNoPosibleException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = repositorio.RegistroNoPosibleExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    repositorio.RegistroNoPosibleExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return repositorio.RegistroNoPosibleExceptionHelper.type ();
  }

}
